<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0d424e12-bcfe-42d9-bc57-c346723d2af9</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.5.1" />
    <PackageReference Include="Elastic.Serilog.Sinks" Version="8.12.3" />
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Templates\email-confirmation.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EmailNotification.Contracts\EmailNotification.Contracts.csproj" />
  </ItemGroup>

</Project>
