<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AccountService.Contracts\AccountService.Contracts.csproj" />
      <ProjectReference Include="..\AccountService.Domain\AccountService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Core" Version="1.1.6" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.7.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FileService.Communication" Version="1.3.4" />
        <PackageReference Include="FileService.Contracts" Version="1.2.3" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.0" />
        <PackageReference Include="MassTransit" Version="8.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="DataModels\UserDataModel.cs" />
    </ItemGroup>
    
</Project>
