<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e9cb2c45-bed9-4cb9-b47a-59c3f2c234fa</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.411.5" />
    <PackageReference Include="Core" Version="1.1.6" />
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.5.1" />
    <PackageReference Include="Framework" Version="1.4.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="MimeTypesMap" Version="1.0.9" />
    <PackageReference Include="Minio.AspNetCore" Version="6.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
    <PackageReference Include="SachkovTech.Issues.Contracts" Version="1.1.4" />
    <PackageReference Include="Scrutor" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.0" />
    <PackageReference Include="sharedkernel" Version="1.1.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="etc\key.pub">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
